### ISSUE TITLE
not working for  Bamboo Slate a4 

### ISSUE THREAD

**Issue by kaushik-mrg** [ngmsoftware/will2svg#1]
Dear Sir,
Thankyou for your code.
I am sorry its not working for me as i am using Bamboo Slate a4 (here in section/media, we have Strokes not path) can you suggest how we can proceed

**Comment by v217** [comment]
I have the slate A4 as well.
I changed line 326 of will_reader.py  to
`
    return input_zip.read('sections/media/strokes2539138681126609676.protobuf')

`
and now I get this error
`
Traceback (most recent call last):
  File "./will_reader_modifiziert.py", line 341, in <module>
    (xData, yData, lineData) = processBuffer(buffer)
  File "./will_reader_modifiziert.py", line 300, in processBuffer
    (x, y, lineWidth) = decodeMessagePacket(messageBytes)
  File "./will_reader_modifiziert.py", line 260, in decodeMessagePacket
    debugPrint(struct.unpack('BBBB',messageBytes[nextPos:]))
struct.error: unpack requires a buffer of 4 bytes

`

**Comment by martinsallandm** [comment]
Hello,

   It must be something on the format of the data generated by the slate.
The unpack for the protobuf is standard, I don't think its protobuff error.
Unfortunately this involves analysing the format with a hex editor to check
manually what is the data. Try to follow the steps I did here:

https://www.allan666.net/reading-vector-graphics/

I hope it helps!

[]'s

**Comment by v217** [comment]
@allanninguem Hi Allan, now I have read your blog post. Not sure if my pull request is still useful.  Anyway Thank you for this great software!

**Comment by martinsallandm** [comment]
Thanks you! I merged your request. Thank you for the contribution!

**Comment by v217** [comment]
Great! Thank you, I've made some more changes, but those are not yet ready for a pull request. I've noticed that you can upload several pages in one will-file.

**Comment by martinsallandm** [comment]
Ha cool!

Pages is something interesting to have %-)

[]'s

**Comment by v217** [comment]
The `will_reader_slate_A4_cairo.py` saves the file with `cairosvg`. [svgtoipe](https://github.com/otfried/ipe-tools) does not support all svg features, so this is a temporary workaround. Since cairo supports natively vector-drawings I don't think it mangles too much with the original svg file.

**Comment by martinsallandm** [comment]
Cool... But remember that the point is just to have the stroke path and
strength, so those are the only two features that matters.

thanks!

[]'s

**Comment by martinsallandm** [comment]
By the way, where are you using this tool? (just out of curiosity %-)

[]'s
